### PR TITLE
remove payment stuff from protocol and edit for clarity

### PR DESCRIPTION
**Pull request by jtremback**
Converted to markdown too, it's easier to work with on Github IMO. Am open to switching it back. @ttk2

### CODE REVIEW

**Comment by ttk2** [comment]
Not a big fan of markdown, I know LaTex is probably really inconvenient for
anyone without a package manager to handle all the addon's I don't even
want to think about how many LaTex packages I have installed.

Automatic citation management is a pretty big deal IMO and a good detailed
set of citations is something that's important to me because it makes
something a lot more understandable (it's documentation for the theory
portion of the program).

For the rest of the changes I have some phrasing nits, probably on my own
writing as it needs to be phrased better. Intermediate nodes only get a
quality metric when they are around to observe for a full ack period, some
sort of trust for neighbors is mandatory if you want to meaningfully act on
the metrics you derive from the acks that sort of stuff, more precise
academic wording is what I'm going for too many cowboy mesh projects where
no one has any idea how it really works because its "based on this" with no
documentation of the ideas or theory behind the changes.

**Comment by jtremback** [comment]
Ok, I'll switch it back to latex.

**Comment by jtremback** [comment]
>  Intermediate nodes only get a quality metric when they are around to observe for a full ack period,

I put "Each node participating in an active connection will be able to estimate an accurate quality metric to at least one of the ends of the connection, once every ack period."

> some sort of trust for neighbors is mandatory if you want to meaningfully act on the metrics you derive from the acks that sort of stuff,

Could you expand on this?

**Comment by ttk2** [comment]
So if we want to act on what we know is a bad route we have to stop routing
to a neighbor, that's a trust system right there, it's just a binary one.
The problem with that is we don't get to isolate the actual malicious node,
just a random other node that ignorantly forwarded it's lies. A more
complex trust system is required to help isolate the actually malicious
node, on the assumption that that node will continue to perform the attack
(if it stops, well problem solved).

So lets say we have a bunch of nodes A-F, at some point F determines that
someone is lying between her and A when she determines this all the other
nodes in the route that have been present for an entire ack period can also
determine this, at which point they put routing through the lying neighbor
on blacklist for a random (think a random single digit number of ack
periods) amount of time and ding that neighbors trust by lets say 10%.
Either you see the attack again right away on a different neighbor and the
entire route continues to shift or things go quiet for a while, then as
timeouts expire various nodes continue operating normally, if they see the
attack again they repeat.

The idea is that this blacklisting process causes the route to a given node
to change significantly, far away nodes are not likely to ever see the
attack again once the route changes a bit, whereas nearby nodes are
probably going to see it again. Since neighbor nodes will always return
from the blacklist timeout to find an attack going on the node is then
isolated with minimal impact to the rest of the network.

You see we have to have some sort of trust system because we need to adjust
this knob over time as well as prevent the attacking node from coming back
with a new identity right away, this is why we raise the trust threashold
for routing as we lower the trust of the malicious neighbor. With some
sanity checks of course.

**Comment by jtremback** [comment]
This was the train of thought that I went down many times when I was trying to design secure routing for Althea. Pretty much the same thing, trying to figure out when to blacklist nodes, the ripple effect etc. The big thing that you brought to the table with Hocnet was reusing the speed test, letting the process be more about correcting inaccurate routes as opposed to punishing perceived misbehavior.

Do you think that this blacklisting process is integral to the system? Why not just have new nodes start out with any routes through them receiving a penalty, and remove the penalty as more traffic is routed?

**Comment by ttk2** [comment]
I think you're just proposing an inverse trust model, where instead of
trusting people by default we distrust them by default and slowly raise the
threshold, from a bootstrapping perspective it takes longer for nodes to
fully integrate into a network even when everyone is being honest. Since
trust (as we're working on it) is local only and not a network wide state
moving nodes would essentially never be trusted to route (which I guess is
fine since they won't have the power to do a good job anyways).

If we increase the 'trust' for every period of no bad route I guess we
would end up with a similar system, but with the bridge based system you've
been working on how do we do any sort of non-binary route movement? I mean
either there is a bridge or there isn't, what would we do in batman to
increase the "priority" of a route, maybe allow a link into the routing
table where userspace can decide penalties to the routing metric? that way
we can penalize what we consider to be 'bad' routes without removing them
in a binary fashion?

**Comment by jtremback** [comment]
Let's leave payment and blocking out of it for now, and consider this to simply be an extension to distance-vector that verifies routes.

Let's also make the assumption of a speedtest being absolutely trustable. That is, once we have looked at the signed ack from a destination and compared it to how many packets we have forwarded to it from a source, we *know* the quality of the route. This is probably not completely the case, but bear with me.

What's left to verify now is the quality of all the routes that we only have information about through the distance-vector protocol. These routes are basically unknown. However, if we have routed through a neighbor in the past and found their speed tests to be accurate, we might be able to have some confidence that they are not personally lying about their routes.

In a hypothetical network where every node is separated by 3 hops, if we have built up a high level of confidence in one neighbor, we can be 1/3 more certain that routes going through them are accurate. So we take their route advertisements more seriously by applying some kind of boost to routes going through them. We don't know anything about their neighbors, but they do, and we effectively delegate that decision to them in proportion to how much we are boosting their routes.

So here is what I am proposing:

- We start out building up the distance-vector routes in the normal way.
- As routes start being used, your reusable speed test comes into play.
- The specific destination that the speedtest applies to is updated to the exact results of the speedtest.
- If the speedtest was accurate (or showed that the speed of the route was better than advertised), we also boost all routes through that neighbor.

**Comment by ttk2** [comment]
Ok so a positive and a negative component, we can either boost routes
through that neighbor or reduce routes through the neighbor based on their
reliability in the past when we last verified the speedtests.

This sounds pretty solid, I'm going to try and formalize it and write it up
tonight or tomorrow.

From an implementation perspective we just have batman on a timer go and
look for netlink messages from scrooge with a new list of adjustment
factors for neighbors.

**Pull request merged**
